# Generated by Django 4.2.30 on 2026-09-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('acceptée', 'Acceptée par le vendeur'), ('terminée', 'Terminée'), ('refusée', 'Refusée'), ('annulée', 'Annulée')], default='en_cours', max_length=10),
        ),
    ]
