# Generated by Django 4.2.30 on 2026-08-14 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su', models.CharField(max_length=20, unique=True)),
                ('superficie_ha', models.IntegerField(default=0)),
                ('superficie_ares', models.IntegerField()),
                ('superficie_ca', models.IntegerField()),
                ('superficie_pourcent', models.IntegerField(default=0)),
                ('zone', models.CharField(max_length=100)),
                ('usage', models.CharField(choices=[('residentiel', 'Résidentiel'), ('commercial', 'Commercial'), ('autre', 'Autre')], max_length=20)),
                ('nature', models.CharField(max_length=50)),
                ('prix_reel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prix_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('vendue', 'Vendue'), ('en_negociation', 'En négociation')], default='disponible', max_length=20)),
                ('titre_foncier', models.CharField(blank=True, max_length=255)),
                ('hash_blockchain', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='utilisateurs.utilisateur')),
            ],
        ),
    ]
