# Generated by Django 4.2.30 on 2026-08-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse_ethereum',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
